name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose --target x86_64-unknown-linux-gnu
    - name: Run tests
      run: cargo test --verbose --target x86_64-unknown-linux-gnu
